language: python
python:
  - '3.3'

services:
  - redis-server

install:
  - 'travis_retry pip install -e ".[test]" --use-mirrors'
  - 'travis_retry pip install coveralls --use-mirrors'

script: 'py.test --pep8 --cov vial'

after_success: 'coveralls'
